### ISSUE TITLE
AssertionError: --in BED file "../PCBP1_K562_IDR_peaks.bed" column 4 IDs not unique

### ISSUE THREAD

**Issue by KunFang93** [BackofenLab/RNAProt#6]
Hi, 

I would like to predict RBP binding sites for multiple genomic regions. I first used genomic region from eCLIP's data as Input to train model followed by the tutorial.

Here are the codes I used:
```
## download eclip data for HepG2 PCBP1 eCLIP
wget https://www.encodeproject.org/files/ENCFF940CJE/@@download/ENCFF940CJE.bed.gz
## reformate downloaded data
gunzip -c ENCFF940CJE.bed.gz | awk '{print $1"\t"$2"\t"$3"\t"$4"\t"$7"\t"$6}' > PCBP1_HepG2_hg19_eCLIP.bed
## generate training data
rnaprot gt --in ../PCBP1_HepG2_hg19_eCLIP.bed --out PCBP1_HepG2_gt_out --gtf /data/kun/Softwares/RNAProt/Homo_sapiens.GRCh37.87.gtf.gz --gen /data/kun/Softwares/RNAProt/hg19.2bit --report --seed 1
## train a model
rnaprot train --in PCBP1_HepG2_gt_out --out PCBP1_HepG2_train_out --verbose-train
## evaluting with 5-fold cross validation
nohup rnaprot train --in PCBP1_HepG2_gt_out --out PCBP1_HepG2_cv_train_out --verbose-train --cv 5 &>rnapro_train.log &
## evaluating training
rnaprot eval --gt-in PCBP1_HepG2_gt_out --train-in PCBP1_HepG2_train_out --out PCPB1_HepG2_eval_out --report
```

I successfully run the above command :). Next, I would like to check if some genomic sites contains RBP binding site that I trained. I run
```
rnaprot gp --in ../K562_IDR_peaks.bed --out K562_gp_out --gtf /data/kun/Softwares/RNAProt/Homo_sapiens.GRCh37.87.gtf.gz --gen /data/kun/Softwares/RNAProt/hg19.2bit --train-in PCBP1_HepG2_train_out/
``` 

And the error:
```
Running for you in GP mode ...
Traceback (most recent call last):
  File "/data/kun/miniconda3/envs/rnaprotenv/bin/rnaprot", line 6174, in <module>
    main_gp(args)
  File "/data/kun/miniconda3/envs/rnaprotenv/bin/rnaprot", line 5303, in main_gp
    assert rplib.bed_check_unique_ids(args.in_sites), "--in BED file \"%s\" column 4 IDs not unique. Please provide BED entries with unique column 4 IDs" %(args.in_sites)
AssertionError: --in BED file "../K562_IDR_peaks.bed" column 4 IDs not unique. Please provide BED entries with unique column 4 IDs
```

head 4 line for K562_IDR_peaks.bed
```
chr5    140953457       140953534       K562_IDR  6.63311810187996        -
chr5    140953343       140953457       K562_IDR  6.45093779594036        -
chr5    140953196       140953324       K562_IDR  5.68880917025827        -
chr16   85667536        85667664        K562_IDR  3.12271843516345        +
```

Thanks in advance!
Kun

**Comment by KunFang93** [comment]
Solved by changing col4 with unique ID
```
chr5    140953457       140953534       K562_IDR_1  6.63311810187996        -
chr5    140953343       140953457       K562_IDR_2  6.45093779594036        -
chr5    140953196       140953324       K562_IDR_3  5.68880917025827        -
chr16   85667536        85667664        K562_IDR_4 3.12271843516345        +
```
with command
```
awk '{print $1"\t"$2"\t"$3"\t"$4"_"NR"\t"$5"\t"$6}'  K562_IDR_peaks.bed > K562_IDR_peaks.bed
```
